$json = Get-Content -Raw -Encoding UTF8 "data/roadmap.json" | ConvertFrom-Json

$json.topics[0].content = "<h3>Что такое переменные?</h3><p>Переменная — это ячейка памяти, в которую программа может сохранять значения. В Java каждая переменная имеет строкгий тип, определяющий, что именно в ней хранится.</p><h3>Основные примитивные типы:</h3><ul><li><code>int</code>: Целочисленные значения (например, 10, -5, 1000).</li><li><code>double</code>: Числа с плавающей точкой/дробные (например, 3.14, 9.99).</li><li><code>char</code>: Одиночный символ, пишется в одинарных кавычках (например, 'A', '1').</li><li><code>boolean</code>: Логический тип, принимающий только <code>true</code> (истина) или <code>false</code> (ложь).</li></ul><h3>Примеры объявления:</h3><pre><code>int age = 18; `ndouble price = 19.50; `nboolean isStudent = true; `nchar grade = 'A';</code></pre><p><b>Строки (Текст):</b> Для текста используется ссылочный тип <code>String</code>, который пишется с заглавной буквы. Текст оформляется в двойных кавычках:<br><code>String text = `"Привет, мир!`";</code></p><p><b>Константы:</b> Если значение не должно изменяться, перед типом ставится слово <code>final</code>:<br><code>final double PI = 3.14159;</code></p>"

$json.topics[1].content = "<h3>Условные операторы</h3><p>Ветвление позволяет программе принимать решения на основе заданных условий. Основной инструмент — конструкция <code>if-else</code>.</p><pre><code>int temp = 25;`nif (temp > 30) {`n    System.out.println(`"Жарко!`");`n} else if (temp > 20) {`n    System.out.println(`"Тепло`");`n} else {`n    System.out.println(`"Холодно`");`n}</code></pre><h3>Логические операторы</h3><p>Сложные условия можно комбинировать:</p><ul><li><code>==</code> (равно), <code>!=</code> (не равно)</li><li><code>&&</code> (логическое И) — оба условия должны быть верны.</li><li><code>||</code> (логическое ИЛИ) — хотя бы одно условие должно быть верно.</li><li><code>!</code> (логическое НЕ) — меняет условие на противоположное.</li></ul><pre><code>int x = 50;`nif (x >= 10 && x <= 100) {`n    System.out.println(`"В диапазоне`");`n}</code></pre><h3>Оператор switch</h3><p>Альтернатива длинным спискам if-else, когда мы проверяем одну переменную на конкретные совпадения:</p><pre><code>int day = 1;`nswitch (day) {`n    case 1: System.out.println(`"Mon`"); break;`n    case 2: System.out.println(`"Tue`"); break;`n    default: System.out.println(`"Other`");`n}</code></pre>"

$json.topics[2].content = "<h3>Методы (Функции)</h3><p>Если один и тот же код требуется выполнять несколько раз, его выделяют в отдельный именованный блок — <b>метод</b>. Это помогает избежать дублирования и делает код читаемым.</p><h3>Структура метода:</h3><pre><code>public static void printGreetings() {`n    System.out.println(`"Hello!`");`n}</code></pre><p>Здесь <code>void</code> означает, что метод ничего не возвращает. Вызывается он так: <code>printGreetings();</code></p><h3>Методы с параметрами и возвращаемым значением</h3><p>Методу можно передать данные (параметры), а он может вернуть результат (вместо void пишется нужный тип):</p><pre><code>public static int sum(int a, int b) {`n    int result = a + b;`n    return result; // Возврат результата`n}`n// Вызов:`nint total = sum(5, 10); // 15</code></pre><h3>Перегрузка методов (Overloading)</h3><p>В Java можно создать несколько методов с одинаковым именем, если они принимают разные аргументы:</p><pre><code>static void print(String msg) { ... }`nstatic void print(int code) { ... }</code></pre>"

$json.topics[3].content = "<h3>Самостоятельная работа №1</h3><p>В этом блоке вам предстоит решить несколько комплексных задач, объединяющих знания о переменных, условиях ветвления и базовых методах.</p><p><b>Совет:</b> Внимательно анализируйте требуемый тип данных в методах, не забывайте про точку с запятой в конце выражений и правильные операторы сравнения (например, <code>==</code> вместо <code>=</code>).</p>"

$json.topics[4].content = "<h3>Для чего нужны циклы?</h3><p>Циклы позволяют выполнять один и тот же блок кода многократно.</p><h3>Цикл for</h3><p>Используется, когда заранее известно, сколько раз нужно повторить действие. Структура: (инициализация; условие; шаг).</p><pre><code>for (int i = 0; i < 5; i++) {`n    System.out.println(`"Итерация `" + i);`n}</code></pre><h3>Цикл while</h3><p>Используется, когда количество повторений неизвестно, но есть условие продолжения.</p><pre><code>int count = 5;`nwhile (count > 0) {`n    System.out.println(count);`n    count--; // Уменьшаем на 1`n}</code></pre><h3>Операторы break и continue</h3><ul><li><code>break;</code> — полностью останавливает и выходит из цикла.</li><li><code>continue;</code> — пропускает текущую итерацию и переходит к следующей проверке.</li></ul>"

$json.topics[5].content = "<h3>Что такое массив?</h3><p>Массив — это контейнер фиксированного размера, содержащий набор элементов одного типа. Индексация в массивах всегда начинается <b>с нуля</b>.</p><h3>Создание и использование</h3><pre><code>// Явная инициализация`nint[] numbers = {10, 20, 30, 40};`n// Доступ к элементу`nSystem.out.println(numbers[0]); // 10`n// Изменение элемента`nnumbers[1] = 99; // Было 20, стало 99</code></pre><h3>Длина массива</h3><p>Для узнавания длины массива используется свойство <code>length</code>. Оно очень полезно при переборе массива в цикле:</p><pre><code>for (int i = 0; i < numbers.length; i++) {`n    System.out.println(numbers[i]);`n}</code></pre><p><b>Внимание:</b> При попытке обратиться к элементу, которого не существует (например, `numbers[10]`), возникнет ошибка `ArrayIndexOutOfBoundsException`.</p>"

$json.topics[6].content = "<h3>Работа со строками</h3><p>Тип <code>String</code> в Java отличается от примитивных типов — это ссылочный тип (объект). Поэтому кроме хранения текста он предоставляет множество полезных методов.</p><h3>Популярные методы строк:</h3><pre><code>String str = `"Hello Java`";`n// Узнать длину строки`nint len = str.length(); // 10`n// Привести к верхнему регистру`nString upper = str.toUpperCase(); // `"HELLO JAVA`"`n// Обрезать пробелы по краям`nString noSpaces = `"  Text  `".trim(); // `"Text`"`n// Получить подстроку (с 6 символа)`nString sub = str.substring(6); // `"Java`"`n// Заменить символы`nString dev = str.replace(`"Java`", `"World`"); // `"Hello World`"</code></pre><h3>Склеивание (Конкатенация)</h3><p>Строки можно склеивать с помощью знака <code>+</code>. Если сложить строку с числом, число тоже станет строкой:</p><pre><code>String s = `"Score: `" + 100; // `"Score: 100`"</code></pre>"

$json.topics[7].content = "<h3>Основы ООП</h3><p>Объектно-ориентированное программирование (ООП) позволяет моделировать реальные вещи с помощью кода. Основные понятия: <b>Класс</b> (чертеж) и <b>Объект</b> (экземпляр, созданный по чертежу).</p><h3>Пример создания класса и объекта:</h3><pre><code>// Описание класса`nclass Car {`n    String model; // Поле`n    void drive() { // Метод`n        System.out.println(model + `" едет.`");`n    }`n}`npublic class Main {`n    public static void main(String[] args) {`n        // Создание объекта`n        Car myCar = new Car();`n        myCar.model = `"BMW`"; // Установка состояния`n        myCar.drive();       // Вызов поведения`n    }`n}</code></pre><h3>Конструкторы</h3><p>Специальный метод, вызывающийся при создании объекта через <code>new</code> для установки начальных значений:</p><pre><code>class User {`n    String name;`n    User(String fullName) { this.name = fullName; }`n}`nUser u = new User(`"Alex`");</code></pre>"

$json.topics[8].content = "<h3>Наследование (Inheritance)</h3><p>Наследование позволяет одному классу получить поля и методы другого класса. Это предотвращает дублирование кода.</p><pre><code>// Суперкласс`nclass Animal {`n    void eat() { System.out.println(`"Ем...`"); }`n}`n// Наследник (используется extends)`nclass Dog extends Animal {`n    void bark() { System.out.println(`"Гав!`"); }`n}`n// Использование:`nDog dog = new Dog();`ndog.eat();  // Унаследовано от Animal`ndog.bark(); // Свой метод</code></pre><h3>Переопределение (Method Overriding)</h3><p>Дочерний класс может изменить поведение, полученное от родителя. Используем аннотацию <code>@Override</code>:</p><pre><code>class Cat extends Animal {`n    @Override`n    void eat() { System.out.println(`"Кот ест рыбу`"); }`n}</code></pre>"

$json.topics[9].content = "<h3>Обработка исключений</h3><p>Исключения (Exceptions) — это возникающие во время работы ошибки (деление на ноль, нет файла и т.д.), которые приводят к крашу программы. Система <code>try-catch</code> позволяет реагировать на них и продолжать работу.</p><h3>Конструкция try-catch</h3><pre><code>try {`n    // Опасный код`n    int res = 10 / 0; `n} catch (ArithmeticException e) {`n    System.out.println(`"Ошибка математики`");`n} catch (Exception e) {`n    // Любые другие ошибки`n    System.out.println(`"Ошибка! `" + e.getMessage());`n} finally {`n    System.out.println(`"Очистка...`"); // Сработает всегда`n}</code></pre><h3>Ключевое слово throw</h3><p>Выброс собственной ошибки:</p><pre><code>if (age < 18) {`n    throw new Exception(`"Меньше 18!`");`n}</code></pre>"

$json.topics[10].content = "<h3>Итоговая Контрольная Работа</h3><p>Поздравляем с прохождением всех основных тем базового Java! 🎉</p><p>В этом блоке вам предстоит решить задачи, которые затронут сразу все пройденные концепты: создание классов, наследование, циклы, работу с массивами, строками и обработку исключений.</p><p>Убедитесь, что вы хорошо продумали логику перед написанием кода, следите за синтаксисом и не бойтесь экспериментировать.</p>"

$json | ConvertTo-Json -Depth 10 | Set-Content "data/roadmap.json" -Encoding UTF8
